// ==UserScript==
// @name         Invidious: Remove ALL CAPS + $ + MrBeast + Keyword + Channel Filter (with exclusions) + Redirect
// @namespace    local
// @version      4.7
// @license      MIT
// @description  Hides search results with ALL CAPS, $ signs, blocked keywords and emojis, or blacklisted channels. Redirects feeds, and allows safe acronyms like NVIDIA or NASA.
// @match        https://yewtu.be/*
// @match        https://inv.nadeko.net/*
// @match        https://invidious.nerdvpn.de/*
// @match        https://inv.perditum.com/*
// @match        https://invidious.f5.si/*
// @match        https://*/watch*
// @match        https://*/feed/popular*
// @match        https://*/feed/trending*
// @grant        none
// @run-at       document-start
// @downloadURL https://update.greasyfork.org/scripts/548558/Invidious%3A%20Remove%20ALL%20CAPS%20%2B%20%24%20%2B%20MrBeast%20%2B%20Keyword%20%2B%20Channel%20Filter%20%28with%20exclusions%29%20%2B%20Redirect.user.js
// @updateURL https://update.greasyfork.org/scripts/548558/Invidious%3A%20Remove%20ALL%20CAPS%20%2B%20%24%20%2B%20MrBeast%20%2B%20Keyword%20%2B%20Channel%20Filter%20%28with%20exclusions%29%20%2B%20Redirect.meta.js
// ==/UserScript==

(function () {
    'use strict';

    // Allowed words (whitelisted acronyms, companies, etc.) that cancels out blockedKeywords and all CAPS filter; emoji filtering still applies.
    const allowedAllCapsPatterns = [
        /^amv$/i,
        /^audio$/i,
        /^ending(s)?$/i,
        /^fanmade$/i,
        /^feat.$/i,
        /^ft.$/i,
        /^lyric$/i,
        /^music video$/i,
        /^offical music/i,
        /^official video$/i,
        /^opening(s)?$/i,
        /^ost$/i,
        /^sleep$/i,
        /^viz$/i,
    ];

    // add your trusted channels here
    const whitelistedChannels = [
        ' - topic',
        'SleepTube - Hypnotic Relaxation', // I use a 3rd party site like y2mate or loader to download this channel's tracks as MP3 files to put on my MP3 player sometimes. :)
    ];

    // Redirect feed pages to search
    /*
        */
    const path = window.location.pathname;
    if (path === '/feed/popular' || path === '/feed/trending') {
        const base = window.location.origin;
        window.location.replace(`${base}/search`);
        return;
    }
    /*
        */

    function isAllCapsWord(word) {
        const clean = word.replace(/[^\p{L}]/gu, ''); // keep letters only
        if (allowedAllCapsPatterns.some(pattern => pattern.test(clean))) return false;
        return clean.length > 2 && clean === clean.toUpperCase();
    }

    // === EARLY HIDE (only UI clutter, not videos!) ===
    function injectEarlyHideCSS() {
        const style = document.createElement('style');
        style.textContent = `
            a[href*="/shorts"],
            .user-field,
            .flex-right > .video-data,
            .pure-u-lg-1-5.pure-u-1:nth-of-type(3),
            .feed-menu,
            footer,
            a[href*="/login?"] {
                display: none !important;
            }
        `;
        document.documentElement.appendChild(style);
    }
    injectEarlyHideCSS();

    const futureYearRegex = /(201[5-9]|202\d|203\d|21\d{2})/; // Year clickbait crap. Example, "First Stream of 2026" etc. Covers 2015-2199 (Pretty sure YouTube will be dead before 2100.)

    const blockedKeywords = [
        "%",
        "'s terrible",
        "alan's universe",
        "can't escape",
        "can't make money",
        "can’t escape",
        "couldn't hide it",
        "didn't go as planned",
        "didn't go to plan",
        "doesn't make sense",
        "don't tell you",
        "don't watch this",
        "dream desk",
        "every day for",
        "he's facing",
        "here's why",
        "he’s facing",
        "i can't live",
        "i can’t",
        "i couldn't lose",
        "i couldn’t lose",
        "i don't",
        "i'll tell you why",
        "i'm back",
        "i'm broke",
        "i'm building",
        "i'm buying",
        "i'm changing",
        "i'm cleaning",
        "i'm creating",
        "i'm dead",
        "i'm done",
        "i'm dying",
        "i'm giving away",
        "i'm going to",
        "i'm helping",
        "i'm hiring",
        "i'm leaving",
        "i'm losing",
        "i'm making",
        "i'm not",
        "i'm opening",
        "i'm poor",
        "i'm quitting",
        "i'm reacting",
        "i'm rebuilding",
        "i'm recreating",
        "i'm repairing",
        "i'm restoring",
        "i'm selling",
        "i'm spending",
        "i'm starting",
        "i'm testing",
        "i'm tired of",
        "i'm tired",
        "i'm transforming",
        "i'm trapped",
        "i'm trying",
        "i'm turning",
        "i'm using",
        "i'm winning",
        "i'm working",
        "i'm",
        "i've bought",
        "i've built",
        "i've changed",
        "i've created",
        "i've done",
        "i've ever",
        "i've failed",
        "i've fixed",
        "i've found",
        "i've given",
        "i've got",
        "i've grown",
        "i've learned",
        "i've lost",
        "i've made",
        "i've met",
        "i've never",
        "i've opened",
        "i've paid",
        "i've quit",
        "i've realized",
        "i've repaired",
        "i've replaced",
        "i've seen",
        "i've spent",
        "i've survived",
        "i've tested",
        "i've tried",
        "i've used",
        "i've won",
        "i've",
        "id never",
        "id quit",
        "id spend",
        "id try",
        "ill build",
        "ill buy",
        "ill change",
        "ill create",
        "ill do",
        "ill fix",
        "ill make",
        "ill never",
        "ill pay",
        "ill spend",
        "ill try",
        "ill win",
        "im back",
        "im broke",
        "im building",
        "im buying",
        "im changing",
        "im cleaning",
        "im creating",
        "im done",
        "im dying",
        "im giving away",
        "im going to",
        "im helping",
        "im hiring",
        "im leaving",
        "im losing",
        "im making",
        "im not",
        "im opening",
        "im poor",
        "im quitting",
        "im reacting",
        "im rebuilding",
        "im recreating",
        "im repairing",
        "im restoring",
        "im selling",
        "im spending",
        "im starting",
        "im testing",
        "im tired",
        "im transforming",
        "im trapped",
        "im trying",
        "im turning",
        "im using",
        "im winning",
        "im working",
        "influencer's career",
        "isn't getting",
        "isn't working",
        "it's happening",
        "it's over",
        "ive bought",
        "ive built",
        "ive changed",
        "ive created",
        "ive done",
        "ive failed",
        "ive fixed",
        "ive found",
        "ive given",
        "ive got",
        "ive grown",
        "ive learned",
        "ive lost",
        "ive made",
        "ive met",
        "ive never",
        "ive opened",
        "ive paid",
        "ive quit",
        "ive realized",
        "ive repaired",
        "ive replaced",
        "ive seen",
        "ive spent",
        "ive survived",
        "ive tested",
        "ive tried",
        "ive used",
        "ive won",
        "i’d never",
        "i’d quit",
        "i’d spend",
        "i’d try",
        "i’ll build",
        "i’ll buy",
        "i’ll change",
        "i’ll create",
        "i’ll do",
        "i’ll fix",
        "i’ll make",
        "i’ll never",
        "i’ll pay",
        "i’ll spend",
        "i’ll try",
        "i’ll win",
        "i’m",
        "i’ve",
        "just won't stop",
        "let's talk",
        "let’s talk",
        "my channel",
        "she's facing",
        "she’s facing",
        "shouldn't have been",
        "shouldn’t have been",
        "the world's",
        "they couldn't",
        "they don't tell",
        "think you can't",
        "wasn't enough",
        "we're not",
        "we're so",
        "won't fail",
        "you didn't know",
        "you don't look",
        "you'll definitely",
        "you're being",
        "you're being",
        "you’re not ready",
        ' ai',
        '!',
        '#',
        '*',
        '.',
        '..',
        '00',
        '?',
        'a broke man',
        'a dark secret',
        'a lie',
        'a loser',
        'a menace',
        'a mistake',
        'a worse',
        'a.i',
        'aaron clarey',
        'aaronclarey',
        'about to burst',
        'absolutely hilarious',
        'accepting my',
        'actually real',
        'actually works',
        'addiction economy',
        'adin',
        'ai ',
        'ai: ',
        'alarming trend',
        'algorithm suck',
        'aliexpress products are',
        'alinity',
        'allegation',
        'almost lost it',
        'alternate universe',
        'amouranth',
        'ancient aliens',
        'annoy',
        'anti-delulu post',
        'apology',
        'are a scam',
        'are crazy',
        'are fighting',
        'are idiots',
        'are lying to you',
        'are out of control',
        'are ruining',
        'are scary',
        'are struggling',
        'are taking over',
        'are worse',
        'around the world in',
        'arrest',
        'artificial intelligence',
        'as you think',
        'asmondgold',
        'audiences hate',
        'awful',
        'awkward',
        'backstabbed',
        'baconmud',
        'bad news for fruit',
        'bank collapse',
        'banned',
        'barely survive',
        'based advice',
        'be like',
        'beautiful free',
        'became the',
        'before it’s too late',
        'behind',
        'belle delphine',
        'ben esherick',
        'big announcement',
        'big ed',
        'biggest mistake',
        'bizarre',
        'blocked me',
        'blows my mind',
        'blox',
        'boring',
        'brain rot',
        'brainrot',
        'breakdown of',
        'breaks the internet',
        'bringing ideas',
        'bullied a',
        'bullies a',
        'but eating',
        'buy me',
        'buy now pay later',
        'buy now pay',
        'buying my',
        'buying',
        'by creep',
        'called me out',
        'called me',
        'called out',
        'came to visit',
        'cancel culture',
        'canceled',
        'cancelled',
        'cant make money',
        'case of',
        'caught on camera',
        'challenge',
        'changed society forever',
        'changed the',
        'changing our world',
        'charlie kirk',
        'chat',
        'chatgpt destroys',
        'chatgpt',
        'cheating',
        'check out',
        'chris titus',
        'claps back',
        'clavicular',
        'commentary',
        'company loyalty in',
        'completely unrecognisable',
        'consent',
        'content creat',
        'controversial',
        'cooked',
        'cost of kicking',
        'could ruin everything',
        'craziest',
        'cringe',
        'cult',
        'cure your delulu',
        'cursed video',
        'daily dose',
        'dangerous trend',
        'dangerous world',
        'dangerously exciting',
        'dangers of dating',
        'dark secret',
        'dark side of betterhelp',
        'dark side of',
        'dark world',
        'darkest',
        'dating a broke',
        'dating horror stories',
        'defend',
        'degenerate',
        'delete this',
        'deletes a random',
        'deserved end',
        'deserves',
        'destroy',
        'destroyed by',
        'destroyed generation',
        'destroyed my',
        'devoid of',
        'dhar mann',
        'did not go as planned',
        'did not go to plan',
        'did something about it',
        'did you know',
        'diddy',
        'die with regrets',
        'dilemma',
        'dirty',
        'disaster',
        'discover',
        'disgust',
        'disney',
        'disrespect',
        'disturbing reason',
        'disturbing',
        'dj cook',
        'dj toenail',
        'do destruction',
        'do not mock',
        'do this now',
        'donald trump',
        'don’t miss this',
        'don’t watch this',
        'doordash',
        'downfall of',
        'drama',
        'dressing up',
        'dropping',
        'drowning themselves',
        'dumb post',
        'elon musk warns',
        'elon',
        'embarass',
        'embarrass',
        'emiru',
        'ended an influencer',
        'ended horribly',
        'entire generation',
        'epic',
        'epstein',
        'euros',
        'even worse',
        'every error',
        'every parent knew',
        'everyone hates',
        'everyone is talking about',
        'everyone lied',
        'everyone wants this',
        'everything is about',
        'everything is falling apart',
        'everything that',
        'everything wrong',
        'expected',
        'explained',
        'exploiting',
        'explor',
        'expose',
        'exposed online',
        'exposed',
        'exposing',
        'face off',
        'fail',
        'faked being',
        'falling apart',
        'faze clan',
        'fazeclan',
        'feel the same anymore',
        'femininity coaches are',
        'files',
        'final warning',
        'final year',
        'finally did it',
        'finally happened',
        'financial regrets people',
        'finished',
        'first bad',
        'fixing a',
        'fixing her',
        'fixing his',
        'flop',
        'fooled people',
        'for strangers',
        'for this',
        'forbidden knowledge',
        'forcing',
        'fortnite',
        'freakiest',
        'from a bedroom',
        'fruit crisis',
        'fruit industry secret',
        'fruit is a disaster',
        'funniest',
        'funny',
        'gambled my',
        'gambling experience',
        'gambling my',
        'game changer',
        'gameplay trailer',
        'gamers nexus',
        'gamersnexus',
        'gaming on a',
        'get the best of me',
        'get worse',
        'gets destroyed',
        'gets scammed',
        'gets worse',
        'getting crazy',
        'getting fillers in',
        'getting sued',
        'getting worse',
        'giveaway',
        'giving strangers',
        'goes wrong',
        'going broke while',
        'gone horribly wrong',
        'gone too far',
        'gone wrong',
        'gonna change',
        'gordon ramsay',
        'got arrested',
        'got away with',
        'got caught',
        'got confirm',
        'got even worse',
        'got the best of me',
        'got worse',
        'greatest lie',
        'greatest trick',
        'grox',
        'h3',
        'had to see this',
        'happy endings at',
        'has arrived',
        'has collapsed',
        'has died',
        'has gone',
        'has lost it',
        'hasan',
        'have to be ugly',
        'hbomberguy',
        'he deserve',
        'he got',
        'he lost it',
        'he ruin',
        'he said',
        'he speed',
        'he tried',
        'her life',
        'her new',
        'her reaction was priceless',
        'here is why',
        'hidden cost of',
        'hidden danger',
        'high end',
        'high maintenance isn’t',
        'hilarious',
        'his life',
        'his new',
        'hit a wall',
        'honest review',
        'horrible',
        'horrifying',
        'horror stories',
        'hot topic',
        'hours',
        'how a',
        'how crime works',
        'how i',
        'how one',
        'how the world',
        'how the',
        'how this person',
        'how to ruin',
        'huge change',
        'hyperinflation warning',
        'i (legally)',
        'i 3d printed',
        'i abandoned',
        'i abused',
        'i accidentally',
        'i achieved',
        'i acquired',
        'i adopted',
        'i almost died',
        'i almost',
        'i am already',
        'i am dead',
        'i am running',
        'i amazed',
        'i analyze',
        'i analyzed',
        'i angered',
        'i answered',
        'i asked',
        'i ate',
        'i attempt',
        'i attempted to',
        'i audited',
        'i awakened',
        'i babysat',
        'i banned',
        'i bargained',
        'i beat',
        'i became',
        'i blackmailed',
        'i blamed',
        'i bought',
        'i box',
        'i broke',
        'i brought',
        'i built',
        'i burned',
        'i butchered',
        'i calculated',
        'i can\'t believe',
        'i cancelled',
        'i can’t believe',
        'i can’t live',
        'i captured',
        'i cast',
        'i caught',
        'i challenged',
        'i changed',
        'i cheated',
        'i cleaned',
        'i cloned',
        'i coded',
        'i collapsed',
        'i competed',
        'i confessed',
        'i confront',
        'i conquered',
        'i control',
        'i convinced',
        'i copied',
        'i corrupted',
        'i could',
        'i crashed',
        'i create',
        'i created',
        'i cried',
        'i crossed',
        'i cut',
        'i deliver',
        'i destroyed',
        'i did',
        'i disappeared',
        'i discovered',
        'i disguised',
        'i disqualified',
        'i dj',
        'i dominated',
        'i donate',
        'i donated',
        'i double',
        'i download',
        'i drained',
        'i earned',
        'i eliminated',
        'i endured',
        'i engineered',
        'i enraged',
        'i enter',
        'i escaped',
        'i experienced',
        'i experimented',
        'i exploited',
        'i explored',
        'i exposed myself',
        'i exposed',
        'i failed to',
        'i failed',
        'i fake',
        'i fasted',
        'i fell for a',
        'i fell into',
        'i fixed',
        'i flew',
        'i fooled',
        'i forced',
        'i forgave',
        'i found',
        'i froze',
        'i gambled',
        'i gaslit',
        'i gave',
        'i got banned',
        'i got fired',
        'i got hacked',
        'i got scammed',
        'i got trapped',
        'i got',
        'i grew',
        'i guessed',
        'i hacked',
        'i had',
        'i hatch',
        'i hate',
        'i have hidden',
        'i have no',
        'i have to',
        'i help',
        'i hire',
        'i hired',
        'i hit',
        'i hung',
        'i hunted',
        'i ignored',
        'i imprisoned',
        'i infiltrated',
        'i inherited',
        'i interrupted',
        'i invaded',
        'i invested',
        'i investigated',
        'i isolated',
        'i joined',
        'i kidnapped',
        'i killed',
        'i launch',
        'i learned the truth',
        'i learned',
        'i left',
        'i legally',
        'i let greed',
        'i lied',
        'i lived',
        'i lose',
        'i lost my',
        'i lost',
        'i made',
        'i manipulated',
        'i mastered',
        'i messed up',
        'i met',
        'i monitored',
        'i moved',
        'i nearly died',
        'i never thought',
        'i only ate',
        'i opened',
        'i ordered',
        'i outsmarted',
        'i overdosed',
        'i overworked',
        'i paid',
        'i panicked',
        'i perform',
        'i picked',
        'i played',
        'i pranked',
        'i predicted',
        'i pretended',
        'i print',
        'i profited',
        'i proved',
        'i punished',
        'i put',
        'i questioned',
        'i quit',
        'i rage quit',
        'i reacted',
        'i realized',
        'i rebuilt',
        'i recorded',
        'i recreate',
        'i rejected',
        'i removed',
        'i repaired',
        'i replaced',
        'i reset',
        'i responded',
        'i resurrected',
        'i revealed',
        'i risked',
        'i ruined',
        'i sabotaged',
        'i sacrificed',
        'i sail',
        'i saved',
        'i saw',
        'i scammed',
        'i sent',
        'i serve',
        'i set up',
        'i shared',
        'i shocked',
        'i should',
        'i showed',
        'i shred',
        'i simulated',
        'i slept',
        'i snuck',
        'i sold',
        'i solved',
        'i spent',
        'i stalked',
        'i started',
        'i starved',
        'i stayed',
        'i stealth',
        'i stole',
        'i studied',
        'i sue',
        'i summoned',
        'i surpassed',
        'i surprised',
        'i survived on',
        'i survived',
        'i suspended',
        'i swipe',
        'i switched',
        'i taught',
        'i technically',
        'i tested if',
        'i tested',
        'i threatened',
        'i threw',
        'i told',
        'i took',
        'i tortured',
        'i traded',
        'i trained',
        'i transform',
        'i trapped',
        'i travel',
        'i trick',
        'i tried to',
        'i tried',
        'i trusted',
        'i turned',
        'i uncovered',
        'i unleashed',
        'i unlocked',
        'i uprooted',
        'i used to',
        'i used',
        'i vandalized',
        'i violated',
        'i visited',
        'i waited',
        'i wanna',
        'i want to',
        'i warned',
        'i was a',
        'i was forced',
        'i was mention',
        'i was on',
        'i was',
        'i went',
        'i wiped',
        'i witnessed',
        'i woke up',
        'i won',
        'i wore',
        'i worked for',
        'i wrecked',
        'i wrote',
        'i yelled',
        'i\'m in this',
        'im releas',
        'immortal rise',
        'impossible',
        'in trouble',
        'inappropriate',
        'incelfication',
        'increasingly worse',
        'influencer marketing is',
        'influencer',
        'insane',
        'inside the mind',
        'inside the',
        'inspired by',
        'instagram',
        'insufferable',
        'insulting',
        'internet hate',
        'internet is furious',
        'internet new epidemic',
        'into a panic',
        'into madness',
        'is advancing',
        'is all over',
        'is bleak',
        'is brutal',
        'is crazy',
        'is dead',
        'is desperate',
        'is diabolic',
        'is disgust',
        'is doomed',
        'is dying',
        'is easy',
        'is free',
        'is going to be true',
        'is going',
        'is hard',
        'is on life support',
        'is out of control',
        'is over',
        'is pathetic',
        'is real',
        'is scary',
        'is spineless',
        'is stuck',
        'is taking over',
        'is terrible',
        'is the worst',
        'is this the end',
        'is toxic',
        'is tragic',
        'is weird',
        'is worse',
        'is... easy',
        'isnt a theory anymore',
        'isn’t a theory anymore',
        'is… easy',
        'it die',
        'it\'s finally over',
        'it\'s time to',
        'its happening',
        'its trash',
        'it’s happening',
        'jack doherty',
        'job security is',
        'just change',
        'just dropped',
        'just lost',
        'keep you broke',
        'keeps getting',
        'kicking kids out',
        'kids out too',
        'killed',
        'l nerd',
        'last chance',
        'laughs at',
        'leaked',
        'learning',
        'left me',
        'legendary',
        'life changing',
        'linkedin',
        'linus sebastian',
        'linus tech tips',
        'linus',
        'linustechtips',
        'linux vs windows',
        'linux’s big moment',
        'literally me',
        'live stream',
        'logan paul',
        'loneliness economy',
        'lost her',
        'lost his',
        'ludwig',
        'made for me',
        'made me',
        'make your videos',
        'making luxury',
        'making',
        'marvel',
        'massive leak',
        'me worse',
        'media forever',
        'meme',
        'might be real',
        'millionaire',
        'mind blowing',
        'minecraft',
        'minutes',
        'mizkif',
        'more powerful',
        'most anticipated',
        'most hated',
        'most irresponsible',
        'most mysterious',
        'most toxic',
        'most useless',
        'mr beast',
        'mr best',
        'mr. beast',
        'mr. best',
        'mr.beast',
        'mrbeast',
        'musk',
        'must watch',
        'my cat is',
        'my current',
        'my dumb',
        'my event',
        'my experience',
        'my first',
        'my friend',
        'my game',
        'my girlfriend',
        'my greatest',
        'my league',
        'my life is over',
        'my losses',
        'my mental',
        'my money',
        'my paycheck',
        'my problem',
        'my relationship',
        'my response',
        'my tough',
        'my tweet',
        'my valuable',
        'my value',
        'my video',
        'my youtube',
        'mystery solved',
        'name',
        'nature’s mistake',
        'never ending chaos',
        'new epidemic',
        'new scam',
        'next level',
        'nightmare',
        'nina lin',
        'no backbone',
        'no longer a theory',
        'no longer alive',
        'no one talks about',
        'no rules',
        'nobody ask',
        'nobody cares',
        'nobody knows why',
        'nobody noticed',
        'nobody talks about',
        'nortorious',
        'not a theory anymore',
        'not going well',
        'not in jail',
        'notorious',
        'now!',
        'nyjah huston',
        'of our',
        'of your life',
        'official trailer',
        'only eating',
        'openai secret',
        'optimiz',
        'organizing my life',
        'oscura verdad',
        'our big',
        'our dream',
        'our fault',
        'our friend',
        'our relationship',
        'out of context',
        'overconsumption is',
        'own fault',
        'owned',
        'pastry that',
        'pay for stranger',
        'pay later gets',
        'perfectly balanced',
        'pewdiepie',
        'plot to',
        'poison',
        'pokimane',
        'portrait video nanny canon',
        'prank',
        'predator factory',
        'pregnancy horror stories',
        'prettier you wake',
        'prison affairs why',
        'prison affairs',
        'propaganda',
        'protecting their kids',
        'proved everyone',
        'psychotic',
        'qtcinderella',
        'quitting youtube',
        'racist',
        'random system32',
        'rant',
        'rapid rise',
        'rate my',
        'rates',
        'rating',
        'react',
        'reacting',
        'reaction',
        'reacts',
        'reality',
        'really dark',
        'reasons i hate',
        'reasons why',
        'reddit stories',
        'reddit story',
        'reddit',
        'remove my',
        'replied',
        'reply',
        'respond',
        'responding to the allegation',
        'review the',
        'review',
        'rhinoplasty regrets what',
        'rhinoplasty regrets',
        'richer than',
        'riding with',
        'right now!',
        'rise of',
        'risking your eyes',
        'robert pg',
        'roblox',
        'ronaldo',
        'ruin your',
        'ruined by',
        'ruined her',
        'ruined his',
        'ruined',
        'ruining her',
        'ruining his',
        'ruining our lives',
        'ruining your',
        'rules for life',
        'running out of seeds',
        'satisfying',
        'saved lives',
        'saves life',
        'saves lives',
        'scammed their way',
        'scammers out-dumb themselves',
        'scare you',
        'secret history of',
        'seedless fruit',
        'selling',
        'sent adults into',
        'shakeup',
        'shane dawson',
        'shannon sharpe',
        'she deserve',
        'she faked being',
        'she got',
        'she ruin',
        'she said',
        'she tried',
        'shocking inflation',
        'shocking',
        'shorts',
        'should not',
        'sick secret',
        'silent disaster',
        'skin bleaching and',
        'skynet moment',
        'slowly giving',
        'smosh',
        'so much better',
        'so much money',
        'social media',
        'sora 1',
        'sora 2',
        'sponsor',
        'spying on you',
        'squid game',
        'sssniperwolf',
        'stalking',
        'starbucks bear cups',
        'still panic',
        'stopped',
        'stream highlight',
        'streamer',
        'streetsmart',
        'subscribe',
        'sucks now',
        'switch from',
        'switched back',
        'switched to',
        'switching back',
        'switching from',
        'switching to',
        'sydney sweeney',
        'take down',
        'taken over',
        'talking',
        'tattoo regret the',
        'tattoo regret',
        'taylor swift',
        'teach you about',
        'teaser',
        'tech is doomed',
        'terrify',
        'test my',
        'tested my',
        'testing my',
        'than you think',
        'than you thought',
        'thank you all',
        'thank you for everything',
        'thank you guys',
        'that got me',
        'that made me',
        'that you have',
        'that you never',
        'the absolute',
        'the ai uprising',
        'the alarming',
        'the best way',
        'the best',
        'the biggest',
        'the bubble will burst',
        'the cancel',
        'the coolest',
        'the creepiest',
        'the dark truth',
        'the day',
        'the death of',
        'the dumbest',
        'the end of',
        'the evil',
        'the fake',
        'the fall of',
        'the fascinating',
        'the fight for',
        'the first person',
        'the future',
        'the hidden',
        'the horrors',
        'the market is crashing',
        'the moment',
        'the most dangerous',
        'the most',
        'the mysterious',
        'the problem',
        'the radical',
        'the reason',
        'the ridiculous',
        'the scariest',
        'the secret',
        'the strange',
        'the toxic',
        'the truth about',
        'the victim',
        'the worst',
        'they wanted',
        'this broke me',
        'this can’t be real',
        'this changes everything',
        'this explains everything',
        'this has to be',
        'this is a problem',
        'this is for',
        'this is horrible',
        'this is how',
        'this is not a drill',
        'this is the best',
        'this is what happens',
        'this is what',
        'this is why',
        'this video',
        'this viewer',
        'this won’t last long',
        'threat to nature',
        'tik tok',
        'tiktok',
        'tim pool',
        'times worse',
        'to survive',
        'too far',
        'top ',
        'top 10',
        'top 5',
        'torment',
        'toxic perfection',
        'tragic tale',
        'tragic tale',
        'trap house braiders',
        'travesty',
        'tried ruin',
        'tried to ruin',
        'truly massive',
        'trust me',
        'try not to laugh',
        'tráiler oficial',
        'turn violent',
        'turned on',
        'turning a free',
        'turning free',
        'turning salvaged',
        'twitch',
        'uglier you sleep',
        'ultimate',
        'unbelievable',
        'undeniable proof',
        'under the knife',
        'unpaid',
        'unusual',
        'viewer',
        'viral',
        'wait for it',
        'waiting to happen',
        'want you to',
        'wants you to',
        'war on children',
        'warn you',
        'warning for everyone',
        'warning for humanity',
        'was a joke',
        'was a tragedy',
        'was absolute',
        'was scary',
        'watch me',
        'watch this before',
        'watch until the end',
        'we all did',
        'we built',
        'we design',
        'we found',
        'we got this instead',
        'we hate',
        'we interview',
        'we laugh',
        'we need to talk',
        'we need to',
        'we play',
        'we thought',
        'we took',
        'we tried',
        'we turn',
        'we watch',
        'we were wrong about',
        'wedding nightmares and',
        'weeks pregnant',
        'weird encounter',
        'weird things',
        'weirdest',
        'went all in',
        'what actually happen',
        'what happens if',
        'what if',
        'what life look',
        'what no one tells you',
        'what really happened',
        'what they don’t teach you',
        'why ',
        'why i',
        'why seedless',
        'why this',
        'why we',
        'why women date',
        'wild dating horror',
        'will be bankrupt',
        'will be hated',
        'will collapse',
        'will end',
        'wish every parent',
        'with no exploits',
        'without a',
        'women date prisoners',
        'women go under',
        'won\'t save us',
        'won\'t save you',
        'working hard and',
        'worse now',
        'worse than i',
        'worse than we',
        'worst crime',
        'worst idea',
        'worst video',
        'worst',
        'yall are going',
        'yall are gonna',
        'years in',
        'yes really',
        'you are not safe',
        'you did not know',
        'you have to see',
        'you laugh',
        'you must know',
        'you need for',
        'you need to',
        'you should',
        'you wake up',
        'you want to',
        'you won\'t believe',
        'you won’t believe',
        'you won’t survive this',
        'your brain',
        'your money',
        'your stream',
        'youtube drama',
        'youtube earn',
        'youtube suck',
        'youtube took down',
        'youtuber',
        'you’ll go broke',
        '| au',
        '£',
        '…',

        // Additions to filter mainstream ragebait / geopolitical drama
        'china',
        'dubai',
        'russia',
        'gaza',
        'trump',
        'putin',
        'north korea',
        'iran',
        'netanyahu',
        'ukraine',
        'syria',
        'venezuela',
        'india',
        'turkey',
        'israel',
        'palestine',
        'brazil',
        'myanmar',
        'africa',
    ];


    const blockedChannels = [
        "Scott's Snippets",
        "alan's universe",
        "alex o'connor",
        "bon appétit",
        "conor o'dwyer",
        "director's cut",
        "it's blanko",
        "it'sagundam",
        "kat 'n chat",
        "kent's tech world",
        "l' immigré parisien",
        "lana's life",
        "lei's looking glass",
        "let's game it out",
        "lily's diary",
        "love coach",
        "luke o’sullivan",
        "mike o'brien",
        "nae's laugh",
        "rick'sf1addiction",
        "sam o'nella academy",
        "scott's stash",
        "stavvy's world clips",
        "terror ted’s tales",
        "that's football",
        "the fish'n canada show",
        "tod's",
        "we're in hell",
        "xkcd's what if",
        "zach's tech turf",
        ' - ',
        '10 minute steam deck gamer',
        '2 and 20',
        '2 danny 2 furious',
        '3.paradis',
        '3blue1brown',
        '4o3o1',
        '5-minute crafts',
        '60 minutes',
        '74 gear',
        '83 weeks with eric bischoff',
        '9ine playz',
        'a life after layoff',
        'a4',
        'aaj tak',
        'aaronclarey',
        'aayu rhymes',
        'academy of ideas',
        'according to nicole',
        'acheeto',
        'acne studios',
        'action retro',
        'actual jake',
        'actual justice warrior',
        'adam conover',
        'adam martyn',
        'adam ruins everything',
        'adam savage\’s tested ',
        'adam something',
        'adam taggart | thoughtful money',
        'adam taggart | thoughtful money®',
        'adhemz',
        'aevy tv',
        'afc asian cup',
        'afp news agency',
        'after skool',
        'aftv',
        'agc andy',
        'ahoy',
        'airrack',
        'aj toys',
        'al jazeera',
        'al jokes',
        'alan becker',
        'alan chen',
        'alan’s universe',
        'alejo igoa',
        'alex ah sue',
        'alex meyers',
        'alexander avila',
        'alexx carpio',
        'alinity',
        'all in the kitchen',
        'all things secured',
        'all time',
        'alltime10s',
        'alofokeradioshow',
        'aloisnl',
        'alphasniper97',
        'alphastein',
        'alt shift x',
        'ambient renders',
        'amd',
        'ami paris',
        'anaya kandhal',
        'andrew huberman',
        'andrew tate',
        'andy & alex',
        'anglers unlimited',
        'angry guy',
        'angryjoeshow',
        'animal cruelty watch',
        'animal sanctuary',
        'annie elise',
        'annoying orange',
        'answer in progress',
        'aphmau',
        'app tutorial',
        'app ultra',
        'apple',
        'aquisi',
        'arcade craniacs',
        'arcas: the man of style',
        'area52',
        'art chad',
        'arthur bailey',
        'arvin ash',
        'ary digital',
        'asgct',
        'ashistudio',
        'asiabits',
        'asian dad energy',
        'asmongold tv',
        'asmongold',
        'asmr',
        'associated press',
        'astrum',
        'asumsaus',
        'atelier juana martín',
        'augusttheduck',
        'austin evans',
        'awakenwithjp',
        'awita',
        'baablu and dream',
        'baby anna - kids songs',
        'baby shark - pinkfong',
        'baby xavi',
        'babybus - kids songs and cartoons',
        'bad5',
        'badmouse productions',
        'bailey sarian',
        'balenciaga',
        'balmain',
        'bangtantv',
        'barbara bui',
        'barely sociable',
        'barking up',
        'barn burner',
        'barstool yak',
        'bass talk live',
        'bass university',
        'bassmaster',
        'bazar du grenier',
        'baztiktok',
        'bbc',
        'be amazed',
        'be smart',
        'beam in serie',
        'beardmeatsfood',
        'beast react',
        'beast',
        'beautiful relaxation',
        'beeyt',
        'behind the castle walls',
        'bein sports usa',
        'belle delphine',
        'bellular news',
        'belyves',
        'ben azelart',
        'ben claremont',
        'ben eater',
        'ben shapiro',
        'benaminute',
        'beneleven',
        'bengal',
        'beniju',
        'benijugoso',
        'benmoyal',
        'berleezy',
        'bese',
        'best fails',
        'betillo',
        'better bachelor',
        'bfordlancer',
        'big a',
        'big data factor',
        'bigclivedotcom',
        'bigtime',
        'biju rithvik',
        'bilel',
        'bill wurtz',
        'bindaas tv',
        'biographics',
        'biography',
        'bionic',
        'bispo bruno leonardo',
        'bittersnake',
        'bizarre videos',
        'blackpink',
        'blake the snake',
        'blast gaming',
        'blinddave',
        'bloodydisgusting',
        'bloomberg',
        'blueworldtv',
        'blumineck',
        'bm sculptures',
        'bnn bloomberg',
        'bob does sports and 2 more',
        'bobbybrocoli',
        'bobicraft',
        'boffy',
        'bog',
        'bonfire ambience',
        'booba – cartoon for kids',
        'bottega veneta',
        'bounding into comics',
        'boxoffice',
        'boy boy',
        'brain blaze',
        'brandon sanderson official',
        'brave wilderness',
        'brawl stars',
        'brent rivera',
        'brentech',
        'brewski',
        'brian tyler cohen',
        'brick technology',
        'brickcraft',
        'brickology productions',
        'bright side',
        'bringus studios',
        'britec09',
        'bro tips',
        'brodie robertson',
        'brut india',
        'bubbinz',
        'build series',
        'bunbunvt',
        'bunhat',
        'business english benjamin · engvid',
        'business insider',
        'buzzfeedvideo',
        'caedrel',
        'caleb hammer',
        'call of duty highlights',
        'call of duty league',
        'camilla araujo',
        'canal kondzilla',
        'canceledmma',
        'candace owens',
        'caoz',
        'capcorgitv',
        'captain chaos',
        'captain disillusion',
        'capture the magic',
        'carrerita',
        'cars & bids',
        'carter',
        'carter2k',
        'carwow',
        'casablanca paris',
        'caseoh',
        'casey neistat',
        'casey simpson',
        'cash',
        'cashblox',
        'cassidy mceown',
        'casually explained',
        'cat trumpet',
        'catalyst',
        'catching killers',
        'cayla with a c',
        'caylus',
        'caylusblox',
        'cbc',
        'cboystv',
        'cecilie bahnsen',
        'celebrity drama',
        'cerostv',
        'cg anime fan',
        'cg5',
        'cgp grey',
        'chanel',
        'channel 4 news',
        'channel 4',
        'channel frederator',
        'charlie survival',
        'chasing chano',
        'chch news',
        'chess.com',
        'chibidoki',
        'chichu tv bird',
        'chichu tv',
        'chief sweet',
        'chiku rhymes',
        'chilling scares',
        'chintu chinki ka pariwar cartoon',
        'chintu chinki ki comedy',
        'chris heria',
        'chris stuckmann reactions',
        'chris stuckmann',
        'chris titus tech',
        'chris williamson',
        'christian dior',
        'christophe',
        'christopher flannigan',
        'chubbyemu',
        'chuchu tv',
        'chud logic',
        'chuuymine',
        'cinema wins',
        'cinemassacre',
        'cinemastix',
        'circletoonshd',
        'citynews',
        'civvie11',
        'ciência todo dia',
        'clash royale',
        'clavicular',
        'cleetus mcfarland',
        'cleo abram',
        'clipcove',
        'clique productions',
        'clownfish tv clips',
        'clownfish tv',
        'clutch gaming highlights',
        'cnbc',
        'cnc kitchen',
        'cnet',
        'coach kolton',
        'cocker spaniel world',
        'coco tv rhymes',
        'cocomelon',
        'code bullet',
        'cody & ko',
        'codyslab',
        'coffeezilla',
        'coldfusion',
        'cole hastings',
        'colin and samir',
        'colinfurze',
        'collins key',
        'colors tv',
        'comedy shorties',
        'comme des garçons',
        'complexly',
        'computerphile',
        'connor is lost',
        'connordawg',
        'construct57',
        'controversial opinions',
        'cookierun: kingdom',
        'corridor crew',
        'coryxkenshin',
        'cozy screen',
        'cozy wood',
        'cp24',
        'crashcourse',
        'crazy deep',
        'crazy pranks 24/7',
        'crazy rants',
        'cristina turner',
        'critical role',
        'ctv news',
        'cufboys',
        'culture vulture',
        'curl manitoba',
        'curtis shaw tv',
        'cyber dopamine',
        'cybercpu tech',
        'czynnamon',
        'dafuq!?boom!',
        'dagar',
        'daily dose',
        'daily fails',
        'daily jesus prayers devotional',
        'dakblake',
        'dakotatalks',
        'dallin and bella',
        'dallmyd',
        'dani',
        'danirep',
        'dankpods',
        'danny duncan',
        'danny gonzalez',
        'danomc',
        'dantdm',
        'dantic',
        'dareen younes',
        'dark5',
        'dash roblox',
        'dash',
        'datruthdt',
        'dave mckeegan',
        'dave mercer',
        'dave2d',
        'david bombal',
        'david dobrik',
        'daz games',
        'dazn boxing',
        'dead air vhs',
        'dead by daylight',
        'deadwingdork',
        'dear nature',
        'death battle',
        'deck wizard',
        'decoder with nilay patel',
        'decoding the unknown',
        'decoy',
        'deep dive with',
        'deep humor',
        'def noodles',
        'definitely not definitive',
        'defunctland',
        'dennyx',
        'derrick thompson',
        'destiny clips',
        'destiny',
        'dexerto',
        'dhar mann',
        'dhruv rathee',
        'diablo',
        'dialogue works',
        'diamondbolt',
        'dice kayek',
        'digital foundry',
        'ding dong bells',
        'dis unlimited',
        'disneyville',
        'disparu',
        'distrotube',
        'diy perks',
        'djmariio',
        'dobre brothers',
        'dochard',
        'doctor mike',
        'dodford',
        'doggie',
        'dogloverlikesdoge',
        'doing it with briggs',
        'dokkan world',
        'dolan darkest',
        'dolce&gabbana',
        'dom brack',
        'dominican geek 360',
        'donald j trump',
        'donpanchis',
        'donut',
        'don’t walk, run! productions',
        'doodle and arkey',
        'doublet',
        'doug demuro',
        'dougdoug',
        'dougdougdoug',
        'dr insanity',
        'dr phil',
        'dr sermed mezher',
        'dr strange live',
        'dr. mayim bialik',
        'dr. todd grande',
        'drama alert',
        'dramaalert clips',
        'dreamgen',
        'dreamxd',
        'drew binsky',
        'drew gooden',
        'dries van noten',
        'dropout',
        'drossrotzank',
        'drunken intelligence',
        'druski',
        'dude perfect',
        'dudeperfect clips',
        'dukhilal ka pariwar cartoon',
        'dumpy',
        'dvc fan',
        'dw documentary',
        'dw news',
        'dwarkesh patel',
        'dxtr white',
        'easy diy hacks',
        'easy english online class',
        'eazyspeezy',
        'eckhartsladder',
        'ed4t',
        'eddy burback',
        'egonlab',
        'eidolonentropy',
        'ejimozy',
        'el reino infantil',
        'el robot de platón',
        'el tarot de pluma blanca',
        'el universal',
        'elabrahaham',
        'electroboom',
        'elie saab',
        'elroddd',
        'elvin alcaide',
        'emanuel ungaro',
        'emergency awesome',
        'emily d. baker',
        'emiru',
        'emkay',
        'emma thorne',
        'emplemon',
        'endymiontv',
        'engween',
        'epic gamer moments',
        'epic rap battles',
        'epicexplorationstv en',
        'eric murphy',
        'eroxblox',
        'esl counter-strike',
        'espn mma',
        'esto es',
        'eta prime',
        'eternalised',
        'eternals explained',
        'ethoslab',
        'eudaimonia',
        'euro and travel',
        'euronews',
        'evan cleary',
        'explainingcomputers',
        'explore lucid dreaming',
        'extreme pranksters',
        'exurb1a',
        'eystreem',
        'fabiano',
        'facebook',
        'failarmy',
        'faister gaming',
        'fandom trivia',
        'fantilafun',
        'farfadox',
        'farfadoxvevo',
        'farmer grade',
        'fast hacks',
        'faze clan highlights',
        'faze clan',
        'faze rug',
        'faze',
        'fc barcelona',
        'fede vigevani',
        'feinberg sucks',
        'fern',
        'fgteev',
        'fifa',
        'film cooper',
        'filmonger',
        'fir ssj',
        'fire lit beatbox',
        'fireship',
        'firstpost',
        'firstroboticscompetition',
        'fis ski jumping',
        'flamingo',
        'flaretv',
        'flygame animals',
        'fns',
        'folagor03',
        'folding ideas',
        'foltyn',
        'forbes breaking news',
        'foreign fridays',
        'foreign man',
        'fortnite battle clips',
        'fortnite',
        'forza',
        'foundation for blind children',
        'fox sports',
        'foxplay',
        'fr3ddylua',
        'france inter',
        'francesca liberatore',
        'fredrik knudsen',
        'free documentary',
        'free to choose network',
        'froggydude',
        'funny fails',
        'fuseschool - global education',
        'futcrunch',
        'fvckdh',
        'gabi belle',
        'gabriele colangelo',
        'gadget unboxings',
        'game theory explained',
        'gamegrumps',
        'gameranx',
        'gamerclips',
        'gamers nexus',
        'games with names',
        'gamestar',
        'gamexdata',
        'gaming nexus',
        'gamingshotz',
        'garbage time',
        'gardiner bryant',
        'garrett crespo',
        'garyvee',
        'gdf',
        'geeks + gamers clips',
        'geeks + gamers',
        'geminitay',
        'general sam',
        'genius explained',
        'geography now',
        'georgenotfound',
        'ggèlido',
        'ghost adventures',
        'giambattista valli',
        'giants nation show',
        'gigguk',
        'gingy',
        'giuliana mafra',
        'glitch productions',
        'glitch',
        'global news',
        'glory kickboxing',
        'gnca - gamersnexus consumer advocacy',
        'goblin clips',
        'goldmines',
        'golpotoon bangla',
        'goobers',
        'good morning america',
        'good morning britain',
        'goodtimeswithscar',
        'google arts & culture',
        'google',
        'goragle',
        'gordon ramsay',
        'gossip central',
        'gossip queen',
        'got talent',
        'gq',
        'grammacrackers',
        'greatscott!',
        'green dot aviation',
        'greg doucette',
        'grian',
        'griggs farms llc',
        'grindr',
        'grisgreen',
        'grizzy',
        'grunge channel',
        'guava juice',
        'gucci',
        'gulli bulli safari',
        'h3h3 productions',
        'habitual linecrosser',
        'hablando huevadas',
        'half as interesting',
        'halfsplit',
        'hall of fame clips',
        'hamedloco spielt',
        'hamfrags',
        'hank green',
        'happy gamer',
        'har pal geo',
        'hardlytommynfg',
        'hasan',
        'hasorule',
        'hay day',
        'hbomberguy',
        'healthygamergg',
        'heelvsbabyface',
        'hellabass',
        'helldivers',
        'hellogamestube',
        'heppe',
        'here for the tea',
        'hermès',
        'hew moran',
        'history buffs',
        'history hacks',
        'hodge twins',
        'holy baam',
        'hooandee',
        'hoopflix',
        'hoots hootman',
        'horrible histories',
        'horse in trouble',
        'hothighpriestess',
        'howie mandel does stuff clips',
        'hrk studio',
        'huebi',
        'hugodécrypte - actus du jour',
        'hutchmf',
        'hybe labels',
        'i am athlete',
        'i did a thing',
        'ibaitv',
        'ibxtoycat',
        'ickedmel',
        'ideacity',
        'idksterling',
        'imallexx',
        'imperial',
        'incognito mode',
        'inferno',
        'infinite',
        'influencers in the wild',
        'infobells – hindi',
        'infobells',
        'inquisitormaster',
        'inside edition',
        'insider',
        'inspirational prayers',
        'intel',
        'internet drama',
        'internet gossip',
        'internet historian',
        'internet oddities',
        'intheclutch ent',
        'into the shadows',
        'investigates!',
        'investornews',
        'is gogeth',
        'isaac butterfield',
        'ishowspeed',
        'island hopper tv',
        'isorrowproductions',
        'issei',
        'italianbach',
        'itsfunneh',
        'itsjanke',
        'itsjustinesworld',
        'itv news',
        'j aubrey',
        'jack & oscar',
        'jack clips',
        'jack cocchiarella',
        'jack doherty',
        'jacksepticeye clips',
        'jacksepticeye',
        'jacob geller',
        'jaidenanimations',
        'jake paul vlogs',
        'jake paul',
        'jake rasmussen',
        'jakeka akakke',
        'jakkuh',
        'jaks attacks',
        'jam campus',
        'jamari',
        'james julier art tutorials',
        'james romero',
        'jamie social',
        'janky rondo',
        'jason mcbason',
        'jason nash',
        'jay feng',
        'jay foreman',
        'jay shuffleboson',
        'jayingee',
        'jaystation',
        'jayztwocents',
        'jcs - criminal psychology',
        'jean paul gaultier',
        'jeanne friot',
        'jeff fm',
        'jeff geerling',
        'jehx sin control',
        'jehxtp',
        'jelly',
        'jenna phipps',
        'jennaphipps',
        'jeremy fielding',
        'jeremy jahns',
        'jerryrigeverything',
        'jesser',
        'jet lag: the game',
        'jettwest',
        'jev',
        'jez',
        'jim browning',
        'jimmy donaldson',
        'jimmy here',
        'jimmy robins',
        'jimmythegiant',
        'jlr© investigates!',
        'jmancurly',
        'joe bart games',
        'joe bartolozzi',
        'joe fazer',
        'joe forgets',
        'joe regrets',
        'joe scott',
        'joey engelman',
        'john hammond',
        'john wolfe',
        'johnny harris',
        'johnny minecraft',
        'johnnycanal',
        'jomboy media',
        'jonah aragon',
        'jondres gc',
        'jondresito gc',
        'jonfx',
        'jontronshow',
        'jordan b peterson',
        'jordan matter',
        'jordan shanks',
        'josh johnson',
        'joshua weissman',
        'joxy',
        'jozhi7',
        'jubilee and the bulwark',
        'jubilee',
        'judelow',
        'juegagerman',
        'jujalag',
        'just trish podcast',
        'justdeleteit',
        'justforfun',
        'justin bieber',
        'justsaysteven',
        'justsomejacob',
        'jynxzi live',
        'jynxzi',
        'k asante',
        'kahaniyo ka',
        'kai trump',
        'kajudyt',
        'kamsandwich',
        'kamswy',
        'karl jobst',
        'karly fuun',
        'kat blaque',
        'katie maloney',
        'katliente',
        'kaye',
        'keemstar clips',
        'keemstar drama',
        'keepittechie',
        'ken',
        'kenzo',
        'kesto',
        'kevu',
        'khabir outdoors',
        'khan academy',
        'kids channel india',
        'kids diana show',
        'kids planet',
        'kiki chanel',
        'killianthecrafter',
        'kimpro',
        'kinocheck',
        'kitboga',
        'kitchen nightmares',
        'kl bro',
        'km punk',
        'koseki bijou ch. hololive-en',
        'kot4q',
        'krabby krew',
        'kraoesp',
        'kreekcraft',
        'krefix',
        'ksi',
        'kubz scouts',
        'kurtis conner',
        'kurzgesagt',
        'kxng',
        'kyle hill',
        'l3wg everything',
        'lAdbible stories',
        'la disidencia',
        'lacoste',
        'ladoo kids hindi',
        'lalafun',
        'lando kalriz',
        'lankybox',
        'lastweektonight',
        'late checkout',
        'late night with seth meyers',
        'latte asmr',
        'laughingdiscowatch',
        'laura malvoyante',
        'laurenzside',
        'law by mike',
        'law&crime',
        'lawful masses with leonard french',
        'lazarbeam',
        'lazy masquerade',
        'lck global',
        'leah ashe',
        'learn french with alexa',
        'learn linux tv',
        'lec',
        'legacy farmer',
        'legaleagle',
        'leicester city fc fan channel | ltidtv',
        'lemmino',
        'lemonade stand',
        'lets read!',
        'lexi rivera',
        'lgr',
        'life hack master',
        'life in 5 minutes',
        'life story tv',
        'lights are off',
        'like nastya',
        'like stories of old',
        'lillepekka',
        'lilsimsie',
        'lincoln center theater',
        'linus tech tips',
        'liquid marshall',
        'liron segev',
        'lisbug',
        'litkovska official',
        'little remy food',
        'little rusty buckets',
        'liuss',
        'live',
        'llm',
        'lmg clips',
        'loaded0',
        'lockdownlife',
        'lockpickinglawyer',
        'lofi chill music',
        'lofi girl',
        'logan paul',
        'lol esports vods español casteos ibai',
        'lol esports',
        'loljaysonx2',
        'looloo kids',
        'lotus eaters',
        'louaista',
        'louis rossmann',
        'louis vuitton',
        'low level',
        'ls mark',
        'lta español',
        'lucrew',
        'lucy edwards',
        'ludwig',
        'ludwin',
        'luka levi',
        'luke dunkin’s traveling circus',
        'luke smith',
        'luminous by trixie cruz-angeles & ahmed paglinawan',
        'lunduke journal',
        'lyna and mandarina',
        'lyna',
        'm6 info',
        'maamorae',
        'macrumors',
        'madvocate',
        'magic jungle',
        'magical adventures with rhi - mummy of four',
        'maizen',
        'mamekurogouchi',
        'man carrying thing',
        'mandjtv extra',
        'mando',
        'manepear',
        'manlybadasshero',
        'map pack',
        'marathon',
        'mark rober',
        'mark tilbury',
        'markiplier',
        'marques brownlee',
        'marvelous videos',
        'master samwise',
        'mathew matos gillingwater',
        'matrozz',
        'matt loui',
        'matt neff',
        'matt redman',
        'matt walsh',
        'matthew hussey',
        'mattkc',
        'matty matheson',
        'mattyballz',
        'mattybraps',
        'mattysquared',
        'max fosh',
        'max mara',
        'max the meat guy',
        'maximilian dood',
        'maximus',
        'meatcanyon',
        'meateater podcast network',
        'meenyu',
        'mega crit',
        'megaprojects',
        'meidastouch',
        'melt the barrel',
        'memes compilation',
        'memes daily',
        'memology 101',
        'mental outlaw',
        'meshugaman',
        'metaphysical',
        'metrabyte',
        'michael horn',
        'michael knowles',
        'michael mjd',
        'michael reeves',
        'michelle khare',
        'microsoft',
        'microwave society',
        'midnights edge',
        'mighty',
        'miguelillo_rl',
        'milenio',
        'miles in transit',
        'mill house',
        'miller thriller garage',
        'milliethepig',
        'millietwopig',
        'mind blown',
        'minecraft best moments',
        'minezy',
        'mini herios',
        'miniminuteman',
        'minutephysics',
        'misaac',
        'miss rice',
        'miu miu',
        'mixwell',
        'mizkif',
        'mm6 maison margiela',
        'mmg',
        'moarf23',
        'mob entertainment',
        'modern vintage gamer',
        'moist69giraffe',
        'molly burke',
        'momo  travel',
        'money guy',
        'mook spud',
        'more cringe',
        'more perfect union',
        'morecaseoh',
        'morecrunch',
        'moresidemen',
        'morgz',
        'mori',
        'mossi',
        'motivation madness',
        'mouse games',
        'mouse news',
        'mouzakrobat',
        'movieswithmark',
        'mr. geil',
        'mr. nightmare',
        'mrbeast',
        'mrcube6',
        'mrmobile',
        'mrwhosetheboss',
        'mugthief',
        'muhammad furqan bhatti',
        'mujin',
        'mumbo jumbo',
        'munchies',
        'must watch videos',
        'mysterious remote',
        'mythical kitchen',
        'nacho roblox',
        'nacho',
        'nagruxito',
        'nakeyjakey',
        'nakkalites',
        'nanogenix',
        'naomi brockwell tv',
        'naradflix',
        'nasa',
        'nascar on fox',
        'nathaniel bandy',
        'national geographic',
        'national museum of american history',
        'natmongkol thunlisa',
        'nba',
        'nbc bay area',
        'nbc news',
        'ndl',
        'nehera',
        'neko and tora',
        'nelonline',
        'neo',
        'nerdrotic',
        'nerdstalgic',
        'netflix',
        'networkchuck',
        'news.com.au',
        'newsnation and 2 more',
        'newsnation and ross coulthart',
        'nexpo',
        'next level soul podcast',
        'nexxuz world',
        'nfl',
        'ngamshishi',
        'nicholasdeorio',
        'nick collins',
        'nick digiovanni',
        'nick jackson',
        'nick nimmin',
        'nickatnite clips',
        'nico grigg',
        'nico knows tech',
        'niko omilana',
        'nileblue',
        'nilered',
        'nina lin',
        'nintendo',
        'nintendúo',
        'no text to speech',
        'nocturn',
        'noel miller',
        'nogla',
        'noodle',
        'north coast',
        'northernlion',
        'not just bikes',
        'notable people explained',
        'nova lectio',
        'noway4u',
        'nowmedia group',
        'numberphile',
        'nvidia',
        'oddheader',
        'off-white c/o virgil abloh™',
        'official christian tv',
        'official drama clips',
        'offline dylon',
        'offline red',
        'ohnepixel',
        'ohnoitsalexx',
        'olav',
        'old farts fishing',
        'olurinatti',
        'omenasito',
        'omg stories',
        'ompaville',
        'omz',
        'once upon a pip',
        'one minute history',
        'onetake',
        'only diy hacks',
        'only fire',
        'ontan',
        'open thoughts',
        'optimum',
        'orangepeanut',
        'ouest paris',
        'overeasy',
        'overhyped',
        'oversimplified',
        'oxhorn',
        'palace confidential',
        'paluten',
        'pambansang kalikot',
        'pancho',
        'papaplatte gaming',
        'papaplatte uncut',
        'parthedits',
        'pastor kingsley osei - canada',
        'pastra',
        'patrick boyle',
        'patrick cc',
        'paul joseph watson',
        'pbs eons',
        'pbs infinite series',
        'pbs',
        'pc security channel',
        'peaks',
        'peanutbuttergamer',
        'peebs',
        'pelicomic',
        'penguinz0',
        'people make games',
        'peter rabbit',
        'pewdiepie',
        'pexto',
        'pgl',
        'philip defranco',
        'philosophy explained',
        'philosophy tube',
        'pierre cardin',
        'piers morgan uncensored',
        'pierson',
        'pietsmiet',
        'pig is eating slop',
        'pillar of garbage',
        'pka clips',
        'plainrock124',
        'plane view farm',
        'playoverwatch',
        'pleasedavid',
        'pm7',
        'pochipoom',
        'podcast',
        'pogo',
        'pokeshek',
        'pokimane',
        'poly matter',
        'polymatter',
        'pop culture facts',
        'popcorn picks',
        'poplostwins',
        'powder blue',
        'powerfuljre',
        'practical engineering',
        'prada',
        'prageru',
        'prank compilation',
        'prank wars',
        'precogvision',
        'president chay',
        'preston',
        'prestonplayz and 4 more',
        'prestonplayz',
        'primal space',
        'primitive technology',
        'pro gamer clips',
        'project farm',
        'propaganda & co',
        'propelled pingu',
        'pubg highlights daily',
        'purplematter',
        'pursuit of meaning',
        'pursuit of wonder',
        'pwnedbloxx',
        'pwr',
        'qtcinderella',
        'quanta magazine',
        'queen coke francis',
        'quick tech tips',
        'quirky facts',
        'rabanne',
        'radio emmanuel',
        'radio tele eclair',
        'rain melody',
        'rajo end',
        'ramboh',
        'rampy',
        'randall carlson',
        'rant central',
        'raody',
        'raptorgamer',
        'rblx',
        'rbt',
        'rdjavi',
        'reactions',
        'ready to glare',
        'real ben esherick',
        'real crime',
        'real engineering',
        'real life with jack hibbs',
        'reallifelore',
        'rebecca zamolo',
        'redalert',
        'reddit',
        'reel deal sportfishing',
        'reff',
        'reggie',
        'rekrap2',
        'relax night and day - beautiful nature & sounds',
        'relax with tv backgrounds',
        'resident evil',
        'reuters',
        'rhia fam',
        'ricegum',
        'richlev',
        'rick owens',
        'rickmeep',
        'rickyedit',
        'riserecords',
        'riya kids tv',
        'rizado',
        'rob braxman tech',
        'robert pg',
        'robleisiutu',
        'robleisjaja',
        'roblox',
        'robtopgames',
        'rochas',
        'rocky rakoon',
        'rogers tv',
        'rogurt',
        'ronald finger',
        'ronny',
        'rotten mango',
        'rowann',
        'roxicake gamer',
        'rslash',
        'rtgame',
        'rubius z',
        'rubixraptor',
        'runescape',
        'rustynickle40',
        'ryan pictures',
        'ryan trahan',
        'sabin civil engineering',
        'sabine hossenfelder',
        'sacai',
        'sad boyz',
        'safiya nygaard',
        'sagan hawkes',
        'sam & tristan',
        'sam and colby',
        'sambucha',
        'sammy sk football',
        'samtime',
        'sargon of akkad',
        'sas bahu ki jugalbandi',
        'sasha yanshin',
        'sauce',
        'savvynik',
        'sb737',
        'sbs dateline',
        'scambait',
        'scambaiters vs. scammers',
        'scammer payback',
        'scammer',
        'scary videos 24/7',
        'schaffrillas productions',
        'scishow',
        'scott shafer',
        'scott the woz',
        'screen culture',
        'sean aslam',
        'sean tanktop',
        'sebastian lague',
        'sebastiside',
        'second thought',
        'seeker',
        'seeytonic',
        'serious angler - bass fishing podcast and the lure lab – fishing tackle podcast',
        'serious angler - bass fishing podcast',
        'sethy poker',
        'seynotic',
        'seyonic',
        'seyonictypo',
        'seythonic',
        'seytonic',
        'seyttonic',
        'seyytonic',
        'shane dawson',
        'sharkee',
        'sharpness',
        'shawn ryan show',
        'sheeprampage',
        'shemaroo filmi gaane',
        'sheriff labrador - kids cartoon',
        'shidbot420',
        'shneako',
        'shookguy57',
        'short explanations',
        'shortcircuit',
        'side scrollers',
        'side+',
        'sidemen',
        'sideprojects',
        'sideways',
        'sightseeing stan',
        'silvio gamer',
        'simfinity',
        'simon clark',
        'simply cyber - gerald auger, phd',
        'sirdork',
        'situationist',
        'skiddzie',
        'skill up',
        'skip intro',
        'skip the tutorial',
        'skipperynmi',
        'skoottie',
        'sky news',
        'slate',
        'sloan bella',
        'slushy noobz',
        'smartereveryday',
        'smii7y',
        'smii7yplus',
        'smithsonian channel',
        'smosh games',
        'smosh pit',
        'smosh',
        'sniperwolf',
        'snipesnap',
        'social experiment videos',
        'social media drama',
        'socialpark',
        'solace',
        'solid homme official',
        'somber',
        'some ordinary gamer clips',
        'someordinarygamers',
        'something nice with dinano',
        'sonar systems',
        'sonic and friends en español',
        'soreal',
        'sound of winter',
        'soy nabi',
        'soypato',
        'soywelix brookhaven',
        'soywelix',
        'spark',
        'spatnz',
        'spawn wave',
        'special edd',
        'speedrun highlights',
        'speeduniverse',
        'spencer hilbert',
        'spill sesh',
        'spill',
        'spoke',
        'spookston',
        'sportmax',
        'sports highlights',
        'sports yaari',
        'sportsnet',
        'spotlight drama',
        'spreen plus',
        'spreen',
        'sprunki simon',
        'sri chaitanya academy neet',
        'sseth tzeentach',
        'ssethtzeentach',
        'sssniperwolf',
        'ssundee clips',
        'ssundee',
        'stan browney',
        'stand-up maths',
        'stanleymov',
        'stanrp',
        'startalk',
        'stated clearly',
        'steak',
        'stella mccartney',
        'steve mould',
        'steven richter',
        'stevencrowder',
        'stimpee',
        'stinkyasher',
        'stokes twins',
        'storytime videos',
        'street fighter',
        'studio gek',
        'stuff made here',
        'styropyro',
        'summoning salt',
        'sunny and melon',
        'sunnyv2',
        'sunraybee',
        'super eyepatch wolf',
        'supercuts delight',
        'supertf',
        'superwog',
        'surfshark academy',
        'surin k fact and 2 more',
        'surveillance report',
        'susan turiciano juarez',
        'switch on the deck',
        'switched to linux',
        'sydney sweeney',
        'sydney watson',
        'sypherpk',
        'sysHack',
        'systemzee',
        't-series',
        't3rr0r',
        'taakk_official',
        'takemylargemango',
        'tanqr',
        'tantwo',
        'tasting history with max miller',
        'taylor lorenz',
        'taylor swift',
        'taylorswift',
        'tcd',
        'tcnick',
        'tea spill',
        'team futurism',
        'tech hacks daily',
        'tech with mobin',
        'techaltar',
        'techhut',
        'techlinked',
        'techlore',
        'techmoan',
        'technical sagar',
        'technology connections',
        'techquickie',
        'techy plays',
        'techys',
        'ted-ed',
        'tedx talks',
        'tell me a story',
        'teqiyokid',
        'terroriser',
        'tested',
        'th3 twinz',
        'that chief guy',
        'thatguy',
        'the act man clips',
        'the act man',
        'the antibot',
        'the b-team',
        'the b1m',
        'the backlogs',
        'the bootleg boy',
        'the brandon vu',
        'the canadian press',
        'the casual criminalist',
        'the cloud',
        'the comics pals',
        'the connect: with johnny mitchell',
        'the critical drinker',
        'the daily beast',
        'the dark somnium',
        'the digital nomad guy',
        'the economist',
        'the engineering mindset',
        'the film theorists',
        'the fisherman magazine',
        'the game theorists',
        'the gaming zoo',
        'the harry gold show',
        'the hated one',
        'the headphone show',
        'the infographics show',
        'the lab',
        'the late brake show',
        'the learning hive academy',
        'the linux experiment',
        'the lockdown tv',
        'the luncheon lawyer',
        'the misery machine',
        'the mouselets',
        'the mt hoe hts',
        'the new oil',
        'the next layer',
        'the odd1sout',
        'the onion',
        'the ozark podcast',
        'the paint explainer',
        'the pat mcafee show',
        'the primetime',
        'the prof g pod – scott galloway',
        'the pwhl',
        'the q clips',
        'the quartering clips',
        'the root',
        'the scribble scholar',
        'the sims',
        'the sitdown',
        'the slow mo guys',
        'the speedy diver',
        'the spiffing brit',
        'the sun',
        'the take',
        'the telegraph',
        'the thought emporium',
        'the travelling zam',
        'the try guys',
        'the united stand',
        'the wall street journal',
        'the write channel with nicola monaghan',
        'the yard',
        'theautobharat',
        'thebackyardscientist',
        'thebausffs',
        'theburntpeanut',
        'thechiptide',
        'theekwah',
        'thegamerfrommars',
        'thehandsome',
        'theme park stop',
        'theodd1sout',
        'theprimetime',
        'thequartering',
        'therealjanelsmith',
        'thestradman',
        'thetekkitrealm',
        'think before you sleep',
        'thinking critical',
        'thiojoe',
        'this car pod! clips',
        'thisislife',
        'thoughtleaders',
        'three man weave',
        'throp',
        'thugesh',
        'tibees',
        'tierzoo',
        'tik tok compilation',
        'tiliamonya',
        'tim pool',
        'timcast',
        'time',
        'timthetatman',
        'tips official',
        'tldr news global',
        'tldr news',
        'tmartn2',
        'tms | global entertainment',
        'tnickelss',
        'today',
        'toddally',
        'tofu golem',
        'tom ford',
        'tom redington and jason christie fishing',
        'tom redington and josh bertrand fishing',
        'tom redington',
        'tom scott',
        'tom97',
        'tomdark',
        'tommyinnit',
        'tonefrance',
        'top 10 countdowns',
        'topper guild',
        'total os today',
        'towi',
        'toys and colors',
        'tranium',
        'trap lore ross',
        'trebor',
        'trending now',
        'trevor bauer',
        'tri-line',
        'triggernometry',
        'trigrzolt',
        'triết tâm',
        'troom troom',
        'trutv',
        'try',
        'trymacs',
        'tsn',
        'tulas 47',
        'tuntuni cartoon bangla',
        'turbo xtra',
        'turboblox',
        'turkey tom',
        'tuv',
        'tvonenews',
        'twinkle toons',
        'two hot takes',
        'two minute papers',
        'tyler & snowi',
        'tyler oliveira',
        'tyler vitelli',
        'typical gamer',
        'uc berkeley',
        'ufd tech',
        'ukriblox',
        'ultimate gaming',
        'ultra Relax',
        'ultra kwon',
        'unbox therapy clips',
        'unchained_off',
        'unpoetic justice',
        'unspeakable',
        'unusual videos meme',
        'upflip',
        'upper echelon',
        'ur cristiano',
        'vader',
        'valentino',
        'valkyrae',
        'valorant',
        'vanessa wingårdh',
        'vanilbean',
        'vanity fair',
        'vanossgaming',
        'vara dark',
        'vaush',
        'vegas matt',
        'vegetta777',
        'ventures fly co.',
        'veritas',
        'veritasium',
        'versace',
        'vex',
        'vice',
        'videogamedunkey',
        'videogamersvault',
        'villainee',
        'vindooly',
        'viromalous',
        'visual venture',
        'visually impaired designer',
        'viva la dirt league',
        'vlad and niki',
        'vlogbrothers',
        'vogue',
        'voidzilla',
        'vortrox',
        'vox',
        'vsauce',
        'wagertalk tv: sports picks and betting tips',
        'warfronts',
        'watchmojo.com',
        'wave music',
        'wavywebsurf',
        'wdw news today',
        'wdw pro',
        'wehsing',
        'weird facts daily',
        'wemmbu',
        'wendigoon',
        'wendover productions',
        'werlyb',
        'weshammer',
        'westjett',
        'wham baam dashcam',
        'what lurks beneath',
        'whatifalthist',
        'whirow',
        'whiteandnerdytv',
        'whoskeim',
        'wifies',
        'wild hearts stories',
        'wildbrain',
        'wildcat',
        'wildez',
        'will tennyson',
        'william kitten',
        'willjum',
        'willow by cricbuzz',
        'windows',
        'wired',
        'wirtualtv',
        'wolfeyvgc',
        'wolfgang\'s channel',
        'woofer',
        'wwe',
        'xqc',
        'xrjfle',
        'yarnhub',
        'yaymath',
        'yeahmad',
        'yellowflash 2',
        'yms highlights',
        'yoboy pizza',
        'yohji yamamoto',
        'yolo aventuras',
        'youngarts',
        'yrf',
        'yt crazie',
        'zach king',
        'zack telander',
        'zaldaingerous and cliff crochet',
        'zamzam brother',
        'zanny',
        'zcrexpy',
        'ze frank',
        'zee music company',
        'zee tv',
        'zerohedge',
        'zhc',
        'zhong',
        'zimmermann',
        'zoink',
        'élucid',
        'ñeboygamer',
        'анжела дмитришина',
        'булджать',
        'владус',
        'ሲዲ ስፖርት / cd sport',
        '情感關注組',
        '김어준의 겸손은힘들다 뉴스공장',
        '더한섬 thehandsome',
        '𝒞𝑜𝓏𝓎 𝒲𝒶𝓇𝓂 𝒜𝓂𝒷𝒾𝑒𝓃𝒸𝑒',

        // Country-based (general)
        'america',
        'argentina',
        'australia',
        'austria',
        'bangladesh',
        'belgium',
        'brazil',
        'britain',
        'canada',
        'chile',
        'china',
        'colombia',
        'czech',
        'denmark',
        'england',
        'finland',
        'france',
        'germany',
        'ghana',
        'hungary',
        'india',
        'indonesia',
        'ireland',
        'israel',
        'italy',
        'japan',
        'kenya',
        'korea',
        'malaysia',
        'mexico',
        'netherlands',
        'new zealand',
        'nigeria',
        'norway',
        'pakistan',
        'peru',
        'philippines',
        'poland',
        'portugal',
        'romania',
        'saudi arabia',
        'scotland',
        'singapore',
        'south africa',
        'south korea',
        'spain',
        'sweden',
        'switzerland',
        'thailand',
        'turkey',
        'united kingdom',
        'united states',
        'vietnam',
        'wales',

        // 🐟 Fake Animal Rescue / Nature Slop
        'animal angels',
        'animal planet clips',
        'animal rescue tv',
        'animal universe',
        'animal white',
        'animals love 365',
        'capybara friends',
        'cute animals compilation',
        'cute pet vids',
        'fresh sea cooling',
        'life before',
        'moya - animal rescues',
        'ocean life 360',
        'ocean update',
        'pet rescue 24/7',
        'sea grace',
        'wildlife clips daily',
        'wildlife diary',
        'wildlife warriors',
        'wildlife wonders tv',
        'world of animals',

        // 🌌 Fake Space / Science Facts
        'astroexplorers',
        'cosmic wonders tv',
        'cosmos discovery',
        'galactic discoveries',
        'galactic facts hub',
        'infinity wonders',
        'science daily facts',
        'science fact central',
        'space fact zone',
        'space infinity',
        'space mysteries uncovered',
        'universe explorer',

        // 🤖 AI History / Documentary Spam
        'ancient uncovered',
        'boring history to sleep and science to fall asleep to',
        'comfy history',
        'crown & dagger',
        'dark universe',
        'dreamoria',
        'historic discovery',
        'history at night',
        'history time',
        'muse & snooze - bedtime stories for grown ups',
        'mystery recap',
        'shadowed history',
        'sleep and history',
        'sleepy time history',
        'the wicked historian',
        'war historian sleepy and historian sleepy',
        'warpath history',
        'world history archive',

        // 🕹️ Fake Gaming & Meme Slop
        'ai plays',
        'fortnite clips daily',
        'gaming recap',
        'minecraft facts',

        // 🤖 AI-Generated / AI Slop Channels
        'ai deepfake zone',
        'ai explained daily',
        'ai fact hub',
        'ai for humans',
        'ai news daily',
        'ai video creator',
        'auto creator ai',
        'autovoice ai',
        'block legends 90s',
        'courtroom consequences',
        'deep fake news',
        'deepfake channel',
        'deepfake clips',
        'digital drift ai',
        'discover ai',
        'domain films',
        'fantastic captain',
        'foot tech today',
        'hard fork',
        'made vision',
        'movie unlimited',
        'peengo',
        'roboreview',
        'rádio lelé',
        'synthesized reality',
        'thatai coach',
        'the ai grid',
        'the ai-telier',
        'thecutframe',
        'twisted truth',
        'virtual historian ai',
        'wes roth',

        // 🤖 Popular AI-Focused / AI Commentary Channels
        "bobby's adventures ai",
        '1littlecoder',
        '3blue1brown',
        'ai explained',
        'andrej karpathy',
        'bycloud',
        'clever programmer',
        'code_your_own_ai',
        'dave shapiro',
        'deeplearningai',
        'dr alan thompson',
        'dylan_curious',
        'jordan harrod',
        'julia mccoy',
        'ken jee',
        'krish naik',
        'langchain',
        'lex fridman',
        'matt wolfe',
        'matthew berman',
        'mattvidproai',
        'openai',
        'rob miles',
        'sentdex',
        'statquest with josh starmer',
        'tyztir',
        'yannic kilcher',

        // 🧩 Common Slop / Farm Keywords

        '/\bai\b/i', // AI wildcard filter
        'analysis',
        'archive',
        'bible',
        'breakdown',
        'central',
        'comedy',
        'compilation',
        'compilations',
        'courtroom',
        'daily',
        'dashcam',
        'discover',
        'docu',
        'documentary',
        'entertain',
        'explained',
        'explorer',
        'export',
        'facts',
        'fireplace',
        'footage',
        'gaming',
        'generated',
        'highlights',
        'hub',
        'idiots',
        'insider',
        'instagram',
        'kinda funny',
        'linkedin',
        'media',
        'meme culture',
        'meta',
        'moments',
        'motivat',
        'mysteries',
        'network',
        'news daily',
        'news',
        'official',
        'plays',
        'playz',
        'problem',
        'r/',
        'react',
        'reality tv',
        'recap',
        'reddit stories',
        'reddit',
        'review',
        'science facts',
        'secrets',
        'shorts',
        'sport',
        'stock',
        'streamer',
        'talk',
        'tech news',
        'tech',
        'tiktok',
        'trend',
        'twitter',
        'uncovered',
        'unknown',
        'unseen',
        'updates',
        'viral',
        'voice',
        'whatsapp',
        'youtube',
        'zone',
    ];

    // Robust emoji detection
    const emojiRegex = /\p{Extended_Pictographic}/gu;

    function shouldFilterTitle(title) {
        const words = title.split(/[^\p{L}]+/gu); // split on letters
        const lower = title.toLowerCase();

        // 🔴 FUTURE YEAR CLICKBAIT FILTER
        if (futureYearRegex.test(title)) {
            return true;
        }

        // Check allowed ALL-CAPS patterns
        const hasAllowedAllCapsWord = words.some(word =>
                                                 allowedAllCapsPatterns.some(pattern => pattern.test(word))
                                                );
        if (hasAllowedAllCapsWord) return false;

        // Filter ALL-CAPS words outside whitelist
        if (words.filter(isAllCapsWord).length > 0) return true;

        // Blocked keywords
        if (blockedKeywords.some(keyword => lower.includes(keyword))) return true;

        // Emoji check
        if (emojiRegex.test(title)) return true;

        // Filter $ signs
        if (title.includes('$')) return true;

        return false;
    }

    function normalizeName(name) {
        return name
            .trim()                 // remove leading/trailing spaces
            .replace(/\s+/g, ' ')   // normalize multiple spaces
            .toLowerCase();         // lowercase for comparison
    }

    function shouldFilterChannel(channel) {
        const normChannel = normalizeName(channel);
        return blockedChannels.some(name => normChannel.includes(normalizeName(name)));
    }

    function isWhitelistedChannel(channel) {
        const normChannel = normalizeName(channel);
        return whitelistedChannels.some(name =>
                                        normChannel.includes(normalizeName(name))
                                       );
    }

    function normalize(str) {
        return str.replace(/’/g, "'").toLowerCase();
    }

    function filterResults() {
        const boxes = document.querySelectorAll('.h-box');
        if (!boxes.length) return false;

        let filteredCount = 0;

        boxes.forEach(box => {
            const titleEl = box.querySelector('.video-card-row > a > p');
            const channelEl = box.querySelector('.channel-name');

            const title = titleEl?.textContent.trim() || '';
            const channel = channelEl?.textContent.trim() || '';

            const isWhitelisted = isWhitelistedChannel(channel);

            // Always allow channel blocking to win
            if (shouldFilterChannel(channel) && !isWhitelisted) {
                console.log('[Filtered: channel]', channel);
                box.closest('.pure-u-1')?.remove();
                filteredCount++;
                return;
            }

            // If channel is whitelisted, skip ALL title-based filtering
            if (!isWhitelisted && shouldFilterTitle(title)) {
                console.log('[Filtered: title]', title);
                box.closest('.pure-u-1')?.remove();
                filteredCount++;
            }

        });

        return filteredCount > 0;
    }

    // === TARGETED ANTI-FLICKER OVERLAY ===
    function addAntiFlickerOverlay() {
        const columns = document.querySelectorAll('div.pure-u-md-1-4.pure-u-1');
        columns.forEach(col => {
            const overlay = document.createElement('div');
            overlay.className = 'antiFlickerOverlay';
            overlay.style.cssText = `
                position: absolute;
                inset: 0;
                background: #0f0f0f;
                z-index: 9999;
                pointer-events: none;
                opacity: 1;
                transition: opacity 0.25s ease-out;
            `;

            // Ensure column is relative for absolute overlay
            if (getComputedStyle(col).position === 'static') col.style.position = 'relative';

            // Insert overlay as first child
            col.insertBefore(overlay, col.firstChild);
        });
    }

    function removeAntiFlickerOverlay() {
        document.querySelectorAll('.antiFlickerOverlay').forEach(el => {
            requestAnimationFrame(() => el.style.opacity = '0');
            el.addEventListener('transitionend', () => el.remove());
        });
    }

    // Add overlays immediately
    const initOverlay = () => {
        const cols = document.querySelectorAll('div.pure-u-md-1-4.pure-u-1');
        if (!cols.length) {
            requestAnimationFrame(initOverlay); // wait until columns exist
            return;
        }
        addAntiFlickerOverlay();
    };
    initOverlay();

    // Run filtering
    let tries = 0;
    const maxTries = 20;
    const interval = setInterval(() => {
        tries++;
        const hasFiltered = filterResults();

        if (tries >= maxTries || !hasFiltered) {
            clearInterval(interval);
            removeAntiFlickerOverlay();
            console.log('[Invidious Filter] Finished filtering.');
        }
    }, 250);

})();